//super admin token:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0VtcGxveWVlIjpmYWxzZSwiaXNBZG1pbiI6dHJ1ZSwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2NTQyNTU1NTZ9.lPbPe_n04A1XgfnjgQwSrr1kfGdNZkHX5c_Z9FZXh7Q
//Admin token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0VtcGxveWVlIjpmYWxzZSwiaXNBZG1pbiI6dHJ1ZSwiaXNTdXBlckFkbWluIjpmYWxzZSwiaWF0IjoxNjU0MjU1NzI3fQ.nSr5HkPPIIPOw-tat3ZYAytG-tpCSN5I-SK-FylgxaY
//Employee token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0VtcGxveWVlIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaXNTdXBlckFkbWluIjpmYWxzZSwiaWF0IjoxNjU0MjU1NzkwfQ.3ry7f3PhXijNvWCXQ9Z3flyiQFijttnAYIov0DEmJNM

POST http://localhost:3000/login
Content-Type: application/json

{

"email":"bindu123@gmail.com",
"password":"bindu"

}

//to get userType
GET http://localhost:3000/users/usertype/bindu123@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0VtcGxveWVlIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaXNTdXBlckFkbWluIjpmYWxzZSwiaWF0IjoxNjU0NTAzOTQ0fQ.wSECQY_1WKtk_DBQmXTZ-pT1-sA1ApfxytBIVBkvf24
// signup employee,admin,super admin
POST  http://localhost:3000/signup
Content-Type: application/json

{
    "username":"vannuuu",
    "age":"12",
    "skills":"c",
    "email":"lmn@gmail.com",
    "password":"Bin4@1123",
    "role":"employee",
    "gdo":"gdo2"
}

// employee can add new goal and status for particular month
POST  http://localhost:3000/usergoals/addgoalStatus
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0VtcGxveWVlIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaXNTdXBlckFkbWluIjpmYWxzZSwiaWF0IjoxNjU0MTQ4NDY5fQ.INQPgbXNNdFvsr2jV28_otudwIRhQwBoDwIeTR2QeZM

{
    "email":"teju123@gmail.com",
    "goal": "Learn java",
    "status": "Inprogress",
    "month":"2022-06-02"
}

//Employee  can access particualr month goal and status 
GET http://localhost:3000/usergoals/teju123@gmail.com/2022-06-02 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0VtcGxveWVlIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaXNTdXBlckFkbWluIjpmYWxzZSwiaWF0IjoxNjU0MTQ4NDY5fQ.INQPgbXNNdFvsr2jV28_otudwIRhQwBoDwIeTR2QeZM

//Employee can edit goal 
PUT http://localhost:3000/usergoals/editgoal?email=teju123@gmail.com&month=2022-06-01&goal=learn sql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0VtcGxveWVlIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaXNTdXBlckFkbWluIjpmYWxzZSwiaWF0IjoxNjU0MTQ4NDY5fQ.INQPgbXNNdFvsr2jV28_otudwIRhQwBoDwIeTR2QeZM

{
    "goal":"learn datascience"
}


// Employee can edit status of particular month

PUT http://localhost:3000/usergoals/editstatus?email=teju123@gmail.com&month=2022-06-01&status=in progress
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0VtcGxveWVlIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaXNTdXBlckFkbWluIjpmYWxzZSwiaWF0IjoxNjU0MTQ4NDY5fQ.INQPgbXNNdFvsr2jV28_otudwIRhQwBoDwIeTR2QeZM

{
    "status":"completed"
}



// Admin/superAdmin can fetech all employees under his/admin guidance 
GET http://localhost:3000/users/employees/vanu123@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0VtcGxveWVlIjpmYWxzZSwiaXNBZG1pbiI6dHJ1ZSwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2NTQxODMxNzh9.HFQmfIK45LRqaSyK6VowsV-JkjVNtP64Du86QSZ9MuE

// admin and superAdmin can see employee goals for particular month
GET http://localhost:3000/usergoals/teju123@gmail.com/2022-06-01 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0VtcGxveWVlIjp0cnVlLCJpc0FkbWluIjpmYWxzZSwiaXNTdXBlckFkbWluIjpmYWxzZSwiaWF0IjoxNjU0MTQ4NDY5fQ.INQPgbXNNdFvsr2jV28_otudwIRhQwBoDwIeTR2QeZM



// superAdmin operations

GET http://localhost:3000/users/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0VtcGxveWVlIjpmYWxzZSwiaXNBZG1pbiI6dHJ1ZSwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2NTQxODMxNzh9.HFQmfIK45LRqaSyK6VowsV-JkjVNtP64Du86QSZ9MuE








